# Generated by Django 6.0.5 on 2026-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(fields=('nom', 'classe'), name='unique_matiere_par_classe'),
        ),
    ]
