# Generated by Django 6.0.6 on 2026-07-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('learner', 'Learner'), ('student', 'Student'), ('teacher', 'Teacher'), ('manager', 'Manager')], default='student', max_length=20),
        ),
    ]
