# Generated by Django 6.0.5 on 2026-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='video',
            field=models.URLField(blank=True, help_text='Lien YouTube (facultatif)', null=True),
        ),
    ]
