# Generated by Django 6.0.5 on 2026-07-20 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('cours', '0003_cours_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='classes.classe'),
        ),
    ]
