# Generated by Django 6.0.5 on 2026-07-21 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('cours', '0004_cours_classe'),
        ('matieres', '0002_matiere_unique_matiere_par_classe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='classes.classe'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('titre', 'classe', 'matiere'), name='unique_cours_par_classe'),
        ),
    ]
