# Generated by Django 6.0.5 on 2026-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_profil_photo_profil_telephone_alter_profil_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.CharField(blank=True, default=None, max_length=255),
            preserve_default=False,
        ),
    ]
