# Generated by Django 6.0.5 on 2026-07-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_profil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, default='profils/default.png', null=True, upload_to='profils/'),
        ),
    ]
