# Generated by Django 6.0.5 on 2026-07-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('comptes', '0004_alter_profil_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='classes.classe'),
        ),
    ]
