# Generated by Django 6.0.6 on 2026-07-08 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la leçon')),
                ('content', models.TextField(verbose_name='Contenu de la leçon')),
                ('order', models.PositiveIntegerField(verbose_name='Ordre de la leçon')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Cours lié')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
